// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH1dSwg6ZWAVY6xQwOAZj_8jiqQ9xNzt8',
    appId: '1:666303524211:web:d2a48bf5da2e9dde8e6906',
    messagingSenderId: '666303524211',
    projectId: 'cricuser-16820',
    authDomain: 'cricuser-16820.firebaseapp.com',
    storageBucket: 'cricuser-16820.appspot.com',
    measurementId: 'G-Y0PJN78MKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM3PvHTY6Dc75ccv4Iv4cKUlkK1odh6ZI',
    appId: '1:666303524211:android:3b8ccf49e4d074ea8e6906',
    messagingSenderId: '666303524211',
    projectId: 'cricuser-16820',
    storageBucket: 'cricuser-16820.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbpBUd3VpMjz6B5j3Kw9-UNY08e7kveiU',
    appId: '1:666303524211:ios:6446c5f7e46d137a8e6906',
    messagingSenderId: '666303524211',
    projectId: 'cricuser-16820',
    storageBucket: 'cricuser-16820.appspot.com',
    iosBundleId: 'com.example.coachui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbpBUd3VpMjz6B5j3Kw9-UNY08e7kveiU',
    appId: '1:666303524211:ios:6446c5f7e46d137a8e6906',
    messagingSenderId: '666303524211',
    projectId: 'cricuser-16820',
    storageBucket: 'cricuser-16820.appspot.com',
    iosBundleId: 'com.example.coachui',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH1dSwg6ZWAVY6xQwOAZj_8jiqQ9xNzt8',
    appId: '1:666303524211:web:459642e4bff45d398e6906',
    messagingSenderId: '666303524211',
    projectId: 'cricuser-16820',
    authDomain: 'cricuser-16820.firebaseapp.com',
    storageBucket: 'cricuser-16820.appspot.com',
    measurementId: 'G-FTVN3J0W6X',
  );
}
